# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999ef7a968ac0c21036594572ebfa67bcf04279c61231a2cbda2fc02ec11073d4cad25075071584fb22c42cad9fa41eaeda276eec5919500fe1cda777022a0d9

test:
  secret_key_base: 381c0a01d3397beff0deac2511ca0b4526f0a8071d744f5442e8df4f59d5b67957e1ce9c20bf675af717df672a3510bc8dc80ae3d158abbfdc2a0496ea098760

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
